version: "3"
services:
  mail-o-rama:
    build: xrstf/mail-o-rama:postfix
    hostname: mail-o-rama
    ports:
      - "143:143"  # IMAP
      - "993:993"  # IMAPS
      - "25:25"    # SMTP
      - "465:465"  # authenticated TLS-SMTP
      - "587:587"  # TLS-SMTP
    environment:
      # the name of your mailserver, NOT the domains you want to handle on it
      - "HOSTNAME=bundy.net"
      # the opposite of HOSTNAME, i.e. your primary e-mail domain
      - "DOMAIN=bundy.net"
      - "DESTINATION=bundy.net, myserver, localhost"
      - "VIRTUAL_DOMAIN_ALIASES=bundy-family.com, biguns.us"
      - "MESSAGE_SIZE_LIMIT=100240000" # 100MB
      - "SMTPD_MILTERS=inet:localhost:11332" # rspamd
      - "NON_SMTPD_MILTERS="

      # It's your job to provide a TLS certificate and private key. You should
      # probably already have a Let's Encrypt client setup somewhere.
      - "TLS_CERTIFICATE=/ssl/fullchain"
      - "TLS_PRIVATE_KEY=/ssl/privkey"

      # Configure what DKIM private key to use and what the DKIM selector should be.
      - "DKIM_PRIVATE_KEY=/etc/dkimkeys/mail.pem"
      - "DKIM_SELECTOR=mail"

      # If you chose to use the included backup script, you can configure a
      # retention period for your backup files. This is the number of days for
      # which to keep backups.
      - "BACKUP_RETENTION_DAYS=7"

    volumes:
      # See the README on these files.
      - ./mounts/aliases:/etc/mail/aliases:ro
      - ./mounts/domains:/etc/mail/domains:ro
      - ./mounts/accounts:/etc/mail/accounts:ro
      - ./mounts/virtuals:/etc/mail/virtuals:ro

      # add the DKIM private key
      - ./dkim.priv.pem:/etc/dkimkeys/mail.pem:ro

      # This directory holds all mail data for all accounts. This is your
      # holy directory and you should keep regular backups of it.
      - ./mail-data:/var/mail-data

      # mount your TLS certificate and private key;
      # simply mounting the domain directory does not work because the
      # privkey is a symlink; mounting the files directly makes Docker
      # resolve the symlink before mounting
      - /var/lib/acme/live/bundy.net/fullchain:/ssl/fullchain:ro
      - /var/lib/acme/live/bundy.net/privkey:/ssl/privkey:ro
